language: node_js
notifications:
  email: false
before_script: git rev-parse v`jq '.dependencies."hapi-greenkeeper-keeper"' -r package.json`
deploy:
  provider: heroku
  api_key:
    secure: mILDb3Xrn8APcXobhvwbIrSU3OaDmlMgYj+N7+t9v5v5G4LDE1myWTagsI5qTJUcrLrFs6XFuZz6r1HwsKF9xNSuDRdgPeqO4YViDz2FxoHNBTKbLRPq/OZunAFO7ydwDkTV+tfb5LyT9Xo2Lq1fIs8P9NGwHKQ19Qwjujq7oj9r+lzX1bzB6u20xQszvf6P8B5JwH1JogN23dptjEqZRV8ler7tsyf30lPjOxMwEv2uEMnj2jW1/rxWnaJqmfySoAJ2qxihdhWjZRqnpdKw/vosQ6ZLYGSElQSHq0n8hWlAwnA4DoK/HicEEryAuXKBzDYWoYWkmuAUin6cD2H93YYXEtXeQl9KVKmeaUqrnHjgZVmqTCFbWFmLRZTgXUyAxNUga+/28YrltneAPQAO4kyFYDaCGCCaK7otn2z6l4GdTj64gMwBjZICVR86DBrTALrT8QVleMc4wr35wK8ofOWVauvDN2plutOBgZrbDHMhv+7cLs/c6Cagr586e3paQihuVJDZAnwude5+zg0nzIIS7FR2+NSf9eP4ShgVGP2A5yTC7I7X+kD65fe1xVsivCr5vKbSAhbArnvSQS4JmAWMvuDfhkcEmj8koyhImEGyU856lfSOS51uktY42VmnYoJCehUn4wgDde7eWuEJy+l3N7S8o9kYWAIoiBbSWKM=
  app: gk-keeper
  on:
    repo: greenkeeper-keeper/reference-instance
