language: node_js
notifications:
  email: false
deploy:
  provider: heroku
  app: gk-keeper
  on:
    repo: greenkeeper-keeper/reference-instance
  api_key:
    secure: SrkFluTJqAZwyAg5MO7+jrqPDluuSx1RgRwfKSeY5uyvsfPUAl1jDgjvOdPSCbZbqzF5uEr7I6M19MjM3w/EZeGtvwZ37XB1ce3BRZtMK8J8x9fA72OcF6PbcEZ++M0r2tVM5eKthSOem0tgG1Nx3Rs4B4QVxjY7u73UxlMPY/lskPn9Hboz8AcoMe/t8z8jOIghu/8hjZ2FrAoCXd8KMgyri3jFDTGRJD3AVwo/vYiLu4DFR3PobMCzxkFLenTat05iIuS4c/VIsKPED8wI9aNHgL51kcMZUJpECQx2lEry1ZlKYjifWquNZKPcwfeZBCJtQSML5prnKMZGzuMivLn5otReHuLMkotIB+yZelqiHcsC7wwq+wpP9ZZFOgWu6s5mOKfY/hywFXsi3UHmiV6XihiicSRplyA19lr1uM7JZVz90VDmvam8J9j1ZsTJIR5soqQGTcSXUCaxx5lXRaKqsmJbQm+U72l1YcrbfJ88vfImr8vUVnMDQM9lNnV5uTHgxH0mMvABqCnt+GHic052Dzrwz/5TuECPnTv6H5myXebGWdHumUJUWpB50/ntd9xEvggytxFN7emu86uTaUJD4bixN2qh63bJ/8L02Ak81MwVcCfqWSMB6L2VyToOdZgD2+QwLStp69oy6z64RFm47/0oWH0im1Rdz1XC7Nw=
